### PR TITLE
Zotero BibTeX Support

### PR DESCRIPTION
**Pull request by silvia-ivanova-github-rep**
**Description**
Now you can import BibTeX files from Zotero. (see comment in Issue #167)

**Affects**
ImportBibTex class

**Notes for Reviewer**
Please review & comment/approve.

### CODE REVIEW

**Comment by claudia3** [comment]
Month is displayed in author names.

Screenshot_20210415_113101

**Comment by claudia3** [comment]
Test file. Also the own notes are not displayed.
```
@book{eilenberger_2014,
    title = {Der {Tatort} und die {Philosophie}: {Schlauer} werden mit der beliebtesten {Fernsehserie}},
    isbn = {978-3-608-10653-4},
    shorttitle = {Der {Tatort} und die {Philosophie}},
    abstract = {In 20 ebenso einfallsreichen wie zugänglichen Essays denken deutsche Philosophen über die philosophischen Dimensionen der Kult-Serie nach. Adam Soboczynski, Gert Scobel, Cord Riechelmann und viele mehr entdecken übersehene Spuren, legen verdeckte Motive frei, stellen die eigentlich entscheidenden Fragen: Warum soll man eigentlich nicht töten? Wann wäre ein Verbrechen perfekt? Ist jeder Täter schuldig? Was ist eine gute Ausrede? Ermitteln weibliche Kommissare anders? Eine Einführung in die Philosophie des 20. Jahrhunderts und ihre wesentlichen Motive, so spannend und mitreißend wie ein guter Tatort.},
    language = {de},
    publisher = {Tropen},
    author = {Eilenberger, Wolfram},
    month = mar,
    year = {2014},
    anote = {Google-Books-ID: CoERBAAAQBAJ},
    keywords = {Philosophy / Reference, Philosophy / Religious},
    annote = {Test}
}

@book{karmasin2012gestaltung,
	title = {{Die Gestaltung wissenschaftlicher Arbeiten: ein Leitfaden f{\"u}r Seminararbeiten, Bachelor-, Master-und Magisterarbeiten sowie Dissertationen}},
	author={Karmasin, Matthias and Ribing, Rainer},
	year={2012},
	publisher={Wien: Facultas},
        annote={hpkgjogjog}
}

@book{hartmann_2003,
	title = {Von "Stahlnetz" zu "Tatort": 50 Jahre deutscher Fernsehkrimi},
	isbn = {978-3-8288-8567-7},
	shorttitle = {Von "Stahlnetz" zu "Tatort"},
	abstract = {Am 25. Dezember 1952 nahm das Deutsche Fernsehen seinen regelmäßigen Sendebetrieb auf. Schon bald darauf wurden die ersten Fernsehkrimis ausgestrahlt. Seitdem fasziniert dieses Genre die Zuschauer. Auch ein halbes Jahrhundert später sind Krimis zur Freude des Publikums rund um die Uhr auf den meisten Sendern präsent. Die Gründe für diese Erfolgsgeschichte werden im vorliegenden Buch untersucht. Ausgangspunkt ist der Klassiker "Stahlnetz" aus den fünfziger und sechziger Jahren, der bis heute nachhaltigen Einfluss auf den Fernsehkrimi hat. Nach einer Analyse der historischen Reihe im politischen, gesellschaftlichen und medialen Kontext erfolgt eine Gegenüberstellung mit der Neuauflage von "Stahlnetz" im Jahr 1999, die in eine völlig veränderte Medienlandschaft platziert wurde. Die aktuellen Folgen gehen wesentlich auf den Wandel der sozialen und gesellschaftlichen Verhältnisse und den veränderten Publikumsgeschmack ein. Unter Berücksichtigung des Gesamtpanoramas werden die Strukturen des aktuellen Fernsehkrimis herausgearbeitet. Auch der Wandel der geschlechterspezifischen Rollenmuster wird berücksichtigt. Zum Schluss erfolgt eine Gegenüberstellung von "Stahlnetz" und "Tatort," der seit über dreißig Jahren zum Alltag der Fernsehzuschauer gehört. Dieses Buch wendet sich somit an Medienwissenschaftler und alle Anhänger des Fernsehkrimis, die nach weiterführenden Informationen suchen.},
	language = {de},
	publisher = {Tectum Verlag DE},
	author = {Hartmann, Christiane},
	year = {2003},
	anote = {Google-Books-ID: tD5nU97ZS7gC},
	annote={traditionellem PM
        Kapitel 2

    rfdfddffdxfdx
    },
}

@book{welke_2005,
	address = {Radolfzell},
	title = {Die Tatortfolge "Quartet in Leipzig" als gesamtdeutscher Tatort: Analyse einer inszenierten deutsch-deutschen Annäherung},
	isbn = {978-3-936656-19-0},
	shorttitle = {Die Tatortfolge "Quartet in Leipzig" als gesamtdeutscher Tatort},
	url = {http://www.verlaggespraechsforschung.de/2005/welke.htm},
	language = {de},
	urldate = {2021-02-19},
	publisher = {Verl. für Gesprächsforschung},
	author = {Welke, Tina},
	year = {2005},
	anote = {OCLC: 845890416},
	file = {Welke - 2005 - Die Tatortfolge Quartet in Leipzig als gesamtdeu.pdf:/home/sarah/Zotero/storage/RQ4RQPQB/Welke - 2005 - Die Tatortfolge Quartet in Leipzig als gesamtdeu.pdf:application/pdf},
}
```

**Comment by silvia-ivanova-github-rep** [comment]
> Test file. Also why is the google book id set as a note? Shouldn't it be in the additional info book data instead?

Since the BibTexKeys are changed (in order to support BibTeX from Zotero), the shared file is also changed.
The first example has the old format of the shared BibTeX.
Before and after the equal sign there should be " ". e.g.` isbn = {}`
The other examples have not the format that I export from Zotero. I think that we already discussed that a single book cannot have 2 notes. There is why we import all notes as one note for a single book.

**Review by claudia3 — APPROVED** [review]
Due to limited time the incorrect author will not be changed. Also a user can change it her/himself in the BookForm if the information is incorrect.

**Pull request merged**
